#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

OUT=${1:-.env.security}
if [[ -e "$OUT" ]]; then
  echo "Refusing to overwrite existing file: $OUT" >&2
  exit 1
fi
command -v openssl >/dev/null 2>&1 || { echo "openssl is required" >&2; exit 1; }

JWT_TOKEN_SECRET="$(openssl rand -base64 48 | tr -d '=+/\n' | cut -c1-64)"
DB_PASSWORD="$(openssl rand -base64 36 | tr -d '=+/\n' | cut -c1-48)"
REDIS_PASSWORD="$(openssl rand -base64 36 | tr -d '=+/\n' | cut -c1-48)"
JUDGE_TOKEN="$(openssl rand -base64 36 | tr -d '=+/\n' | cut -c1-48)"

cat > "$OUT" <<EOF
# Generated by scripts/generate-security-config.sh
# Keep this file private (permissions 600) and load it through your secret manager.
JWT_TOKEN_SECRET=$JWT_TOKEN_SECRET
DB_PASSWORD=$DB_PASSWORD
REDIS_PASSWORD=$REDIS_PASSWORD
JUDGE_TOKEN=$JUDGE_TOKEN
EOF
chmod 600 "$OUT"
echo "Wrote $OUT (mode 600). Configure these values in Nacos/environment, then restart all services."
